### ISSUE TITLE
Intalling the latest MKL version

### ISSUE THREAD

**Issue by bmwshop** [intel/torch#2]
Following up on this instruction:

Be sure you have installed the lastest MKL version: parallel_studio_xe_2017.

I can't find a free download link - I do see that Parallel Studio is a commercial product.

**Comment by MlWoo** [comment]
@bmwshop 
Thanks for your feedback. The installation script has been modified, and it will download MKL automatically. Please update your code and following up on new instruction.

**Comment by MlWoo** [comment]
@bmwshop 
hi, thanks for your feedback! We have create a new branch named autoDownloadMKL, and you can update your code to try it.

**Comment by MlWoo** [comment]
@bmwshop 
Hi, thanks for your feedback, we have created a new branch named autoDownloadMKL which can help you skip it. Try it.

**Comment by xhzhao** [comment]
fixed by mlwoo
