### ISSUE TITLE
Indexing Failure BUG

### ISSUE THREAD

**Issue by mdushkoff** [intel/torch#8]
I've found a bug in the **index** function which corrupts the data whenever it is not indexing a Tensor across the 1st dimension.

```lua
-- Create random data and random slice indices
x = torch.rand(2000,20000)+3
ind = torch.randperm(x:size(2))[{{1,10}}]:long()

-- Slice x along dimension 2 using the supplied indices in ind
sx = x:index(2,ind)

print("Original Range: " .. x:min() .. "," .. x:max())
print("Slice Range: " .. sx:min() .. "," .. sx:max())
```

The original range should report **3,4** while the sliced range reports an invalid range of **0,~4** (the upper and lower can vary due to randomness, but it should **never** be lower than *3*).

This indicates that the internal data is invalid when using the **index** function.  It certainly has something to do with the size of the matrix itself since you get perfectly fine copies of Tensor sizes of [200,10]:

```lua
x = torch.rand(200,10)+3
ind = torch.LongTensor{1,2,3,4,5,6,7,8,9,10} -- Select all indices in order
sx = x:index(2,ind)
print("Matching: ".. x:eq(sx):sum() .. "/" .. x:nElement())
```

This produces *Matching: 2000/2000*, however the critical point seems to be when the first dimension is *OVER* 720.

A matrix of size [720,10] with the above test produces *Matching: 7200/7200*, however with a matrix of size [721,10] it produces *Matching: 129/7210* which is absolutely not correct.

I'd really appreciate any insights into this error.

**Comment by mingfeima** [comment]
Hi, thx! @mdushkoff is this only observed on intel/torch or it also exists on original torch?
We did rewrite torch.rand() for better performance, however the guy who wrote this @MlWoo is in hospital now. Will get back to this issue when he finished his therapy.

**Comment by mdushkoff** [comment]
@mingfeima I'm so sorry to hear @MlWoo is in the hospital, I hope that they have a swift recovery!

Yes this is only observed in the intel/torch build, and not the original torch build as far as I can tell.  I don't think it has much to do with the torch.rand() function as it has been corrupting data that has been loaded in with torch.load(...) and other structured data.

**Comment by MlWoo** [comment]
@mdushkoff I have looked into the code and identified the problem. After removing the bug, the result seems OK, here is my test:
```bash
th> x = torch.rand(2000,20000)+3
                                                                      [0.4202s]
th> ind = torch.randperm(x:size(2))[{{1,10}}]:long()
                                                                      [0.0012s]
th> sx = x:index(2,ind)
                                                                      [0.0461s]
th> print("Slice Range: " .. sx:min() .. "," .. sx:max())
Slice Range: 3.000022164546,3.9997919152956
                                                                      [0.0001s]
```
Thanks for your reporting the bug.

**Comment by mdushkoff** [comment]
Thank you so much, I really appreciate it!  Looks like this fixed it!
